### ISSUE TITLE
CORs policy enablement

### ISSUE THREAD

**Issue by yuliujpl** [MCLConsortium/mcl.infirmary#3]
## 💁‍♀️ Summary

Clinical-UI portal needs to access the Infirmary API from a different server. Infirmary API currently blocks cross site access. Api throws the following error when attempting to access from a labcas-dev server:
"Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

## 📜 Reproduction

To reproduce as of `Mon Nov 11 15:52 UTC 2020`, do the following:

1. In the browser, open a new, non-incognito browser window.
2. In this window, visit http://labcas-dev.jpl.nasa.gov/clinical-ui
3. Log in following the prompts for username and password.
4. Login will fail with no response on the UI.
5. Check the developer console (ctrl-option-J)

The console should display the CORs error

## 🖥 Context

This seems to occur on Chrome 84.0.4147.125

## 🖼 Screenshot

N/A

**Comment by nutjob4life** [comment]
@yuliujpl I've put into action on mcl-new.jpl.nasa.gov an update to Infirmary that includes these headers with responses:

- Access-Control-Allow-Origin: *
- Access-Control-Allow-Methods: POST,GET,DELETE,PUT,OPTIONS
- Access-Control-Allow-Headers: Origin, Content-Type, Accept, Authorization
- Access-Control-Allow-Credentials: true
- Access-Control-Max-Age: 1728000

Please let me know if these help and if so, go ahead and close the issue. But if they don't work, leave a comment!

**Comment by nutjob4life** [comment]
@yuliujpl I've also asked our sysadmins to make https://mcl-new.jpl.nasa.gov/clinical-ui/ be a reverse-proxy for labcas-dev/clinical-ui. When you access the application through that URL there should be no CORS issues because it's all same-origin.

**Comment by yuliujpl** [comment]
@nutjob4life Thanks Sean! Sorry I just checked github and saw this comment.

I don't see the CORs error anymore but am seeing something else, but I think it might be related to my application itself. Once I troubleshoot and resolve it, then will follow up to confirm. Thanks Sean!

**Comment by yuliujpl** [comment]
Unfortunately, I got this error:
Access to XMLHttpRequest at 'https://mcl-new.jpl.nasa.gov/infirmary//clinicalCores' from origin 'https://labcas-dev.jpl.nasa.gov' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by nutjob4life** [comment]
@yuliujpl what if you try accessing the app from https://mcl-new.jpl.nasa.gov/clinical-ui/

**Comment by yuliujpl** [comment]
Works! Thanks good sir!
